// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/metadata.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1502040966;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'comic_book_maker_core',
        ioDirectory: '../core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  List<PageSummary> crateApiSimpleAddPageImages({
    required String projectId,
    required List<String> sourcePaths,
  });

  AppendImportResult crateApiSimpleAppendCbr({
    required String projectId,
    required String sourcePath,
  });

  AppendImportResult crateApiSimpleAppendCbz({
    required String projectId,
    required String sourcePath,
  });

  AppendImportResult crateApiSimpleAppendEpub({
    required String projectId,
    required String sourcePath,
  });

  ProjectSettings crateApiSimpleChangeProjectInferredImportKind({
    required String projectId,
    required InferredImportKindFrb inferredImportKind,
  });

  String crateApiSimpleCorePing();

  ProjectSummary crateApiSimpleCreateProject({String? title});

  void crateApiSimpleDeletePage({
    required String projectId,
    required String pageId,
  });

  void crateApiSimpleDeleteProject({required String projectId});

  Future<void> crateApiSimpleExportCbz({
    required String projectId,
    required String destinationPath,
    required bool deleteProjectAfterExport,
  });

  Future<void> crateApiSimpleExportEpub({
    required String projectId,
    required String destinationPath,
    required bool deleteProjectAfterExport,
  });

  ImportMetadataSnapshotFrb crateApiSimpleGetImportMetadataSnapshot({
    required String projectId,
  });

  MetadataEditorSchemaFrb crateApiMetadataGetMetadataEditorSchema({
    required ExportFormatFrb exportFormat,
  });

  Metadata crateApiMetadataGetProjectMetadata({required String projectId});

  ProjectSettings crateApiSimpleGetProjectSettings({required String projectId});

  String crateApiSimpleGreet({required String name});

  ImportCbzResult crateApiSimpleImportCbr({required String sourcePath});

  ImportCbzResult crateApiSimpleImportCbz({required String sourcePath});

  ImportCbzResult crateApiSimpleImportEpub({required String sourcePath});

  Future<void> crateApiSimpleInitApp();

  void crateApiSimpleInitLibrary({required String appDataDir});

  List<PageSummary> crateApiSimpleListPages({required String projectId});

  List<ProjectSummary> crateApiSimpleListProjects();

  Metadata crateApiMetadataMergeMetadataFromForm({
    required ExportFormatFrb exportFormat,
    required Metadata base,
    required List<MetadataFieldValueFrb> fieldValues,
    required int pageCount,
  });

  Future<Metadata> crateApiMetadataMetadataDefault();

  String crateApiMetadataMetadataFieldDisplayValue({
    required Metadata metadata,
    required String fieldId,
  });

  Metadata crateApiMetadataMetadataWithCoverPageIndex({
    required Metadata metadata,
    required int coverPageIndex,
  });

  Metadata crateApiMetadataMetadataWithDropdownField({
    required Metadata metadata,
    required String fieldId,
    String? value,
  });

  Metadata crateApiMetadataMetadataWithPageCount({
    required Metadata metadata,
    required int pageCount,
  });

  List<PageSummary> crateApiSimpleReorderPages({
    required String projectId,
    required List<String> orderedPageIds,
  });

  PageSummary crateApiSimpleReplacePageImage({
    required String projectId,
    required String pageId,
    required String sourcePath,
  });

  void crateApiSimpleTouchProject({required String projectId});

  ProjectSettings crateApiSimpleUpdateProjectExportFormat({
    required String projectId,
    required ExportFormatFrb exportFormat,
  });

  Metadata crateApiMetadataUpdateProjectMetadata({
    required String projectId,
    required Metadata metadata,
  });

  ProjectSettings crateApiSimpleUpdateProjectSettings({
    required String projectId,
    required ProjectSettingsUpdate update,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<PageSummary> crateApiSimpleAddPageImages({
    required String projectId,
    required List<String> sourcePaths,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_list_String(sourcePaths, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAddPageImagesConstMeta,
        argValues: [projectId, sourcePaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAddPageImagesConstMeta =>
      const TaskConstMeta(
        debugName: "add_page_images",
        argNames: ["projectId", "sourcePaths"],
      );

  @override
  AppendImportResult crateApiSimpleAppendCbr({
    required String projectId,
    required String sourcePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_append_import_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppendCbrConstMeta,
        argValues: [projectId, sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppendCbrConstMeta => const TaskConstMeta(
    debugName: "append_cbr",
    argNames: ["projectId", "sourcePath"],
  );

  @override
  AppendImportResult crateApiSimpleAppendCbz({
    required String projectId,
    required String sourcePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_append_import_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppendCbzConstMeta,
        argValues: [projectId, sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppendCbzConstMeta => const TaskConstMeta(
    debugName: "append_cbz",
    argNames: ["projectId", "sourcePath"],
  );

  @override
  AppendImportResult crateApiSimpleAppendEpub({
    required String projectId,
    required String sourcePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_append_import_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAppendEpubConstMeta,
        argValues: [projectId, sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppendEpubConstMeta => const TaskConstMeta(
    debugName: "append_epub",
    argNames: ["projectId", "sourcePath"],
  );

  @override
  ProjectSettings crateApiSimpleChangeProjectInferredImportKind({
    required String projectId,
    required InferredImportKindFrb inferredImportKind,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_inferred_import_kind_frb(inferredImportKind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleChangeProjectInferredImportKindConstMeta,
        argValues: [projectId, inferredImportKind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleChangeProjectInferredImportKindConstMeta =>
      const TaskConstMeta(
        debugName: "change_project_inferred_import_kind",
        argNames: ["projectId", "inferredImportKind"],
      );

  @override
  String crateApiSimpleCorePing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCorePingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCorePingConstMeta =>
      const TaskConstMeta(debugName: "core_ping", argNames: []);

  @override
  ProjectSummary crateApiSimpleCreateProject({String? title}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(title, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleCreateProjectConstMeta,
        argValues: [title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateProjectConstMeta =>
      const TaskConstMeta(debugName: "create_project", argNames: ["title"]);

  @override
  void crateApiSimpleDeletePage({
    required String projectId,
    required String pageId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(pageId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleDeletePageConstMeta,
        argValues: [projectId, pageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeletePageConstMeta => const TaskConstMeta(
    debugName: "delete_page",
    argNames: ["projectId", "pageId"],
  );

  @override
  void crateApiSimpleDeleteProject({required String projectId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleDeleteProjectConstMeta,
        argValues: [projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteProjectConstMeta =>
      const TaskConstMeta(debugName: "delete_project", argNames: ["projectId"]);

  @override
  Future<void> crateApiSimpleExportCbz({
    required String projectId,
    required String destinationPath,
    required bool deleteProjectAfterExport,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(destinationPath, serializer);
          sse_encode_bool(deleteProjectAfterExport, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleExportCbzConstMeta,
        argValues: [projectId, destinationPath, deleteProjectAfterExport],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExportCbzConstMeta => const TaskConstMeta(
    debugName: "export_cbz",
    argNames: ["projectId", "destinationPath", "deleteProjectAfterExport"],
  );

  @override
  Future<void> crateApiSimpleExportEpub({
    required String projectId,
    required String destinationPath,
    required bool deleteProjectAfterExport,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(destinationPath, serializer);
          sse_encode_bool(deleteProjectAfterExport, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleExportEpubConstMeta,
        argValues: [projectId, destinationPath, deleteProjectAfterExport],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExportEpubConstMeta => const TaskConstMeta(
    debugName: "export_epub",
    argNames: ["projectId", "destinationPath", "deleteProjectAfterExport"],
  );

  @override
  ImportMetadataSnapshotFrb crateApiSimpleGetImportMetadataSnapshot({
    required String projectId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_metadata_snapshot_frb,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetImportMetadataSnapshotConstMeta,
        argValues: [projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetImportMetadataSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "get_import_metadata_snapshot",
        argNames: ["projectId"],
      );

  @override
  MetadataEditorSchemaFrb crateApiMetadataGetMetadataEditorSchema({
    required ExportFormatFrb exportFormat,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_export_format_frb(exportFormat, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata_editor_schema_frb,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataGetMetadataEditorSchemaConstMeta,
        argValues: [exportFormat],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataGetMetadataEditorSchemaConstMeta =>
      const TaskConstMeta(
        debugName: "get_metadata_editor_schema",
        argNames: ["exportFormat"],
      );

  @override
  Metadata crateApiMetadataGetProjectMetadata({required String projectId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMetadataGetProjectMetadataConstMeta,
        argValues: [projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataGetProjectMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "get_project_metadata",
        argNames: ["projectId"],
      );

  @override
  ProjectSettings crateApiSimpleGetProjectSettings({
    required String projectId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetProjectSettingsConstMeta,
        argValues: [projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetProjectSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "get_project_settings",
        argNames: ["projectId"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  ImportCbzResult crateApiSimpleImportCbr({required String sourcePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_cbz_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleImportCbrConstMeta,
        argValues: [sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportCbrConstMeta =>
      const TaskConstMeta(debugName: "import_cbr", argNames: ["sourcePath"]);

  @override
  ImportCbzResult crateApiSimpleImportCbz({required String sourcePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_cbz_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleImportCbzConstMeta,
        argValues: [sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportCbzConstMeta =>
      const TaskConstMeta(debugName: "import_cbz", argNames: ["sourcePath"]);

  @override
  ImportCbzResult crateApiSimpleImportEpub({required String sourcePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_cbz_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleImportEpubConstMeta,
        argValues: [sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportEpubConstMeta =>
      const TaskConstMeta(debugName: "import_epub", argNames: ["sourcePath"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiSimpleInitLibrary({required String appDataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appDataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleInitLibraryConstMeta,
        argValues: [appDataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitLibraryConstMeta =>
      const TaskConstMeta(debugName: "init_library", argNames: ["appDataDir"]);

  @override
  List<PageSummary> crateApiSimpleListPages({required String projectId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleListPagesConstMeta,
        argValues: [projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListPagesConstMeta =>
      const TaskConstMeta(debugName: "list_pages", argNames: ["projectId"]);

  @override
  List<ProjectSummary> crateApiSimpleListProjects() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_project_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleListProjectsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListProjectsConstMeta =>
      const TaskConstMeta(debugName: "list_projects", argNames: []);

  @override
  Metadata crateApiMetadataMergeMetadataFromForm({
    required ExportFormatFrb exportFormat,
    required Metadata base,
    required List<MetadataFieldValueFrb> fieldValues,
    required int pageCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_export_format_frb(exportFormat, serializer);
          sse_encode_box_autoadd_metadata(base, serializer);
          sse_encode_list_metadata_field_value_frb(fieldValues, serializer);
          sse_encode_i_32(pageCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMetadataMergeMetadataFromFormConstMeta,
        argValues: [exportFormat, base, fieldValues, pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataMergeMetadataFromFormConstMeta =>
      const TaskConstMeta(
        debugName: "merge_metadata_from_form",
        argNames: ["exportFormat", "base", "fieldValues", "pageCount"],
      );

  @override
  Future<Metadata> crateApiMetadataMetadataDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataMetadataDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataMetadataDefaultConstMeta =>
      const TaskConstMeta(debugName: "metadata_default", argNames: []);

  @override
  String crateApiMetadataMetadataFieldDisplayValue({
    required Metadata metadata,
    required String fieldId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_metadata(metadata, serializer);
          sse_encode_String(fieldId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataMetadataFieldDisplayValueConstMeta,
        argValues: [metadata, fieldId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataMetadataFieldDisplayValueConstMeta =>
      const TaskConstMeta(
        debugName: "metadata_field_display_value",
        argNames: ["metadata", "fieldId"],
      );

  @override
  Metadata crateApiMetadataMetadataWithCoverPageIndex({
    required Metadata metadata,
    required int coverPageIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_metadata(metadata, serializer);
          sse_encode_i_32(coverPageIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataMetadataWithCoverPageIndexConstMeta,
        argValues: [metadata, coverPageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataMetadataWithCoverPageIndexConstMeta =>
      const TaskConstMeta(
        debugName: "metadata_with_cover_page_index",
        argNames: ["metadata", "coverPageIndex"],
      );

  @override
  Metadata crateApiMetadataMetadataWithDropdownField({
    required Metadata metadata,
    required String fieldId,
    String? value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_metadata(metadata, serializer);
          sse_encode_String(fieldId, serializer);
          sse_encode_opt_String(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMetadataMetadataWithDropdownFieldConstMeta,
        argValues: [metadata, fieldId, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataMetadataWithDropdownFieldConstMeta =>
      const TaskConstMeta(
        debugName: "metadata_with_dropdown_field",
        argNames: ["metadata", "fieldId", "value"],
      );

  @override
  Metadata crateApiMetadataMetadataWithPageCount({
    required Metadata metadata,
    required int pageCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_metadata(metadata, serializer);
          sse_encode_i_32(pageCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataMetadataWithPageCountConstMeta,
        argValues: [metadata, pageCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataMetadataWithPageCountConstMeta =>
      const TaskConstMeta(
        debugName: "metadata_with_page_count",
        argNames: ["metadata", "pageCount"],
      );

  @override
  List<PageSummary> crateApiSimpleReorderPages({
    required String projectId,
    required List<String> orderedPageIds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_list_String(orderedPageIds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleReorderPagesConstMeta,
        argValues: [projectId, orderedPageIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReorderPagesConstMeta => const TaskConstMeta(
    debugName: "reorder_pages",
    argNames: ["projectId", "orderedPageIds"],
  );

  @override
  PageSummary crateApiSimpleReplacePageImage({
    required String projectId,
    required String pageId,
    required String sourcePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(pageId, serializer);
          sse_encode_String(sourcePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_page_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleReplacePageImageConstMeta,
        argValues: [projectId, pageId, sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReplacePageImageConstMeta =>
      const TaskConstMeta(
        debugName: "replace_page_image",
        argNames: ["projectId", "pageId", "sourcePath"],
      );

  @override
  void crateApiSimpleTouchProject({required String projectId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleTouchProjectConstMeta,
        argValues: [projectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTouchProjectConstMeta =>
      const TaskConstMeta(debugName: "touch_project", argNames: ["projectId"]);

  @override
  ProjectSettings crateApiSimpleUpdateProjectExportFormat({
    required String projectId,
    required ExportFormatFrb exportFormat,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_export_format_frb(exportFormat, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleUpdateProjectExportFormatConstMeta,
        argValues: [projectId, exportFormat],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateProjectExportFormatConstMeta =>
      const TaskConstMeta(
        debugName: "update_project_export_format",
        argNames: ["projectId", "exportFormat"],
      );

  @override
  Metadata crateApiMetadataUpdateProjectMetadata({
    required String projectId,
    required Metadata metadata,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_box_autoadd_metadata(metadata, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMetadataUpdateProjectMetadataConstMeta,
        argValues: [projectId, metadata],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataUpdateProjectMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "update_project_metadata",
        argNames: ["projectId", "metadata"],
      );

  @override
  ProjectSettings crateApiSimpleUpdateProjectSettings({
    required String projectId,
    required ProjectSettingsUpdate update,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_box_autoadd_project_settings_update(update, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleUpdateProjectSettingsConstMeta,
        argValues: [projectId, update],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateProjectSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "update_project_settings",
        argNames: ["projectId", "update"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppendImportResult dco_decode_append_import_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AppendImportResult(
      warnings: dco_decode_list_String(arr[0]),
      addedPageCount: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Metadata dco_decode_box_autoadd_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_metadata(raw);
  }

  @protected
  ProjectSettingsUpdate dco_decode_box_autoadd_project_settings_update(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_project_settings_update(raw);
  }

  @protected
  ComicArchiveContainerFrb dco_decode_comic_archive_container_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ComicArchiveContainerFrb.values[raw as int];
  }

  @protected
  ExportFormatFrb dco_decode_export_format_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ExportFormatFrb.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImportCbzResult dco_decode_import_cbz_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ImportCbzResult(
      project: dco_decode_project_summary(arr[0]),
      warnings: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  ImportMetadataKindFrb dco_decode_import_metadata_kind_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImportMetadataKindFrb.values[raw as int];
  }

  @protected
  ImportMetadataSnapshotFrb dco_decode_import_metadata_snapshot_frb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ImportMetadataSnapshotFrb(
      kind: dco_decode_import_metadata_kind_frb(arr[0]),
      xml: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  InferredImportKindFrb dco_decode_inferred_import_kind_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InferredImportKindFrb.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MetadataFieldSpecFrb> dco_decode_list_metadata_field_spec_frb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_metadata_field_spec_frb)
        .toList();
  }

  @protected
  List<MetadataFieldValueFrb> dco_decode_list_metadata_field_value_frb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_metadata_field_value_frb)
        .toList();
  }

  @protected
  List<MetadataSectionSpecFrb> dco_decode_list_metadata_section_spec_frb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_metadata_section_spec_frb)
        .toList();
  }

  @protected
  List<PageSummary> dco_decode_list_page_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectSummary> dco_decode_list_project_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project_summary).toList();
  }

  @protected
  Metadata dco_decode_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 44)
      throw Exception('unexpected arr length: expect 44 but see ${arr.length}');
    return Metadata(
      title: dco_decode_String(arr[0]),
      series: dco_decode_opt_String(arr[1]),
      issueNumber: dco_decode_opt_String(arr[2]),
      seriesCount: dco_decode_opt_String(arr[3]),
      volume: dco_decode_opt_String(arr[4]),
      alternateSeries: dco_decode_opt_String(arr[5]),
      alternateNumber: dco_decode_opt_String(arr[6]),
      alternateCount: dco_decode_opt_String(arr[7]),
      summary: dco_decode_opt_String(arr[8]),
      notes: dco_decode_opt_String(arr[9]),
      year: dco_decode_opt_box_autoadd_i_32(arr[10]),
      month: dco_decode_opt_box_autoadd_i_32(arr[11]),
      day: dco_decode_opt_box_autoadd_i_32(arr[12]),
      writer: dco_decode_opt_String(arr[13]),
      penciller: dco_decode_opt_String(arr[14]),
      inker: dco_decode_opt_String(arr[15]),
      colorist: dco_decode_opt_String(arr[16]),
      letterer: dco_decode_opt_String(arr[17]),
      coverArtist: dco_decode_opt_String(arr[18]),
      editor: dco_decode_opt_String(arr[19]),
      translator: dco_decode_opt_String(arr[20]),
      publisher: dco_decode_opt_String(arr[21]),
      imprint: dco_decode_opt_String(arr[22]),
      genre: dco_decode_opt_String(arr[23]),
      tags: dco_decode_opt_String(arr[24]),
      web: dco_decode_opt_String(arr[25]),
      languageIso: dco_decode_opt_String(arr[26]),
      format: dco_decode_opt_String(arr[27]),
      blackAndWhite: dco_decode_opt_String(arr[28]),
      manga: dco_decode_opt_String(arr[29]),
      characters: dco_decode_opt_String(arr[30]),
      teams: dco_decode_opt_String(arr[31]),
      locations: dco_decode_opt_String(arr[32]),
      mainCharacterOrTeam: dco_decode_opt_String(arr[33]),
      scanInformation: dco_decode_opt_String(arr[34]),
      storyArc: dco_decode_opt_String(arr[35]),
      storyArcNumber: dco_decode_opt_String(arr[36]),
      seriesGroup: dco_decode_opt_String(arr[37]),
      ageRating: dco_decode_opt_String(arr[38]),
      communityRating: dco_decode_opt_String(arr[39]),
      review: dco_decode_opt_String(arr[40]),
      gtin: dco_decode_opt_String(arr[41]),
      coverPageIndex: dco_decode_i_32(arr[42]),
      pageCount: dco_decode_i_32(arr[43]),
    );
  }

  @protected
  MetadataEditorSchemaFrb dco_decode_metadata_editor_schema_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MetadataEditorSchemaFrb(
      editorTitle: dco_decode_String(arr[0]),
      editable: dco_decode_bool(arr[1]),
      pdfMessage: dco_decode_opt_String(arr[2]),
      sections: dco_decode_list_metadata_section_spec_frb(arr[3]),
      ageRatingPresets: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  MetadataFieldKindFrb dco_decode_metadata_field_kind_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MetadataFieldKindFrb.values[raw as int];
  }

  @protected
  MetadataFieldSpecFrb dco_decode_metadata_field_spec_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MetadataFieldSpecFrb(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      kind: dco_decode_metadata_field_kind_frb(arr[2]),
      required_: dco_decode_bool(arr[3]),
      options: dco_decode_list_String(arr[4]),
      intMin: dco_decode_opt_box_autoadd_i_32(arr[5]),
      intMax: dco_decode_opt_box_autoadd_i_32(arr[6]),
      readOnlyValue: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  MetadataFieldValueFrb dco_decode_metadata_field_value_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MetadataFieldValueFrb(
      fieldId: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  MetadataSectionSpecFrb dco_decode_metadata_section_spec_frb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MetadataSectionSpecFrb(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      fields: dco_decode_list_metadata_field_spec_frb(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PageSummary dco_decode_page_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PageSummary(
      id: dco_decode_String(arr[0]),
      sortIndex: dco_decode_i_32(arr[1]),
      assetPath: dco_decode_String(arr[2]),
      absolutePath: dco_decode_String(arr[3]),
    );
  }

  @protected
  ProjectSettings dco_decode_project_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ProjectSettings(
      exportFormat: dco_decode_export_format_frb(arr[0]),
      inferredImportKind: dco_decode_inferred_import_kind_frb(arr[1]),
      deleteProjectAfterExport: dco_decode_bool(arr[2]),
      useDefaultExportDirectory: dco_decode_bool(arr[3]),
      exportDirectory: dco_decode_opt_String(arr[4]),
      comicArchiveContainer: dco_decode_comic_archive_container_frb(arr[5]),
      useComicArchiveExtension: dco_decode_bool(arr[6]),
    );
  }

  @protected
  ProjectSettingsUpdate dco_decode_project_settings_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProjectSettingsUpdate(
      exportFormat: dco_decode_export_format_frb(arr[0]),
      deleteProjectAfterExport: dco_decode_bool(arr[1]),
      useDefaultExportDirectory: dco_decode_bool(arr[2]),
      exportDirectory: dco_decode_opt_String(arr[3]),
      comicArchiveContainer: dco_decode_comic_archive_container_frb(arr[4]),
      useComicArchiveExtension: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ProjectSummary dco_decode_project_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProjectSummary(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      updatedAtMs: dco_decode_i_64(arr[2]),
      coverThumbnailPath: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppendImportResult sse_decode_append_import_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_warnings = sse_decode_list_String(deserializer);
    var var_addedPageCount = sse_decode_i_32(deserializer);
    return AppendImportResult(
      warnings: var_warnings,
      addedPageCount: var_addedPageCount,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  Metadata sse_decode_box_autoadd_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_metadata(deserializer));
  }

  @protected
  ProjectSettingsUpdate sse_decode_box_autoadd_project_settings_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_project_settings_update(deserializer));
  }

  @protected
  ComicArchiveContainerFrb sse_decode_comic_archive_container_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ComicArchiveContainerFrb.values[inner];
  }

  @protected
  ExportFormatFrb sse_decode_export_format_frb(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ExportFormatFrb.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImportCbzResult sse_decode_import_cbz_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_project = sse_decode_project_summary(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return ImportCbzResult(project: var_project, warnings: var_warnings);
  }

  @protected
  ImportMetadataKindFrb sse_decode_import_metadata_kind_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImportMetadataKindFrb.values[inner];
  }

  @protected
  ImportMetadataSnapshotFrb sse_decode_import_metadata_snapshot_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_import_metadata_kind_frb(deserializer);
    var var_xml = sse_decode_opt_String(deserializer);
    return ImportMetadataSnapshotFrb(kind: var_kind, xml: var_xml);
  }

  @protected
  InferredImportKindFrb sse_decode_inferred_import_kind_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return InferredImportKindFrb.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MetadataFieldSpecFrb> sse_decode_list_metadata_field_spec_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MetadataFieldSpecFrb>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_metadata_field_spec_frb(deserializer));
    }
    return ans_;
  }

  @protected
  List<MetadataFieldValueFrb> sse_decode_list_metadata_field_value_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MetadataFieldValueFrb>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_metadata_field_value_frb(deserializer));
    }
    return ans_;
  }

  @protected
  List<MetadataSectionSpecFrb> sse_decode_list_metadata_section_spec_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MetadataSectionSpecFrb>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_metadata_section_spec_frb(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageSummary> sse_decode_list_page_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectSummary> sse_decode_list_project_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Metadata sse_decode_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_series = sse_decode_opt_String(deserializer);
    var var_issueNumber = sse_decode_opt_String(deserializer);
    var var_seriesCount = sse_decode_opt_String(deserializer);
    var var_volume = sse_decode_opt_String(deserializer);
    var var_alternateSeries = sse_decode_opt_String(deserializer);
    var var_alternateNumber = sse_decode_opt_String(deserializer);
    var var_alternateCount = sse_decode_opt_String(deserializer);
    var var_summary = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_month = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_day = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_writer = sse_decode_opt_String(deserializer);
    var var_penciller = sse_decode_opt_String(deserializer);
    var var_inker = sse_decode_opt_String(deserializer);
    var var_colorist = sse_decode_opt_String(deserializer);
    var var_letterer = sse_decode_opt_String(deserializer);
    var var_coverArtist = sse_decode_opt_String(deserializer);
    var var_editor = sse_decode_opt_String(deserializer);
    var var_translator = sse_decode_opt_String(deserializer);
    var var_publisher = sse_decode_opt_String(deserializer);
    var var_imprint = sse_decode_opt_String(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_opt_String(deserializer);
    var var_web = sse_decode_opt_String(deserializer);
    var var_languageIso = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_opt_String(deserializer);
    var var_blackAndWhite = sse_decode_opt_String(deserializer);
    var var_manga = sse_decode_opt_String(deserializer);
    var var_characters = sse_decode_opt_String(deserializer);
    var var_teams = sse_decode_opt_String(deserializer);
    var var_locations = sse_decode_opt_String(deserializer);
    var var_mainCharacterOrTeam = sse_decode_opt_String(deserializer);
    var var_scanInformation = sse_decode_opt_String(deserializer);
    var var_storyArc = sse_decode_opt_String(deserializer);
    var var_storyArcNumber = sse_decode_opt_String(deserializer);
    var var_seriesGroup = sse_decode_opt_String(deserializer);
    var var_ageRating = sse_decode_opt_String(deserializer);
    var var_communityRating = sse_decode_opt_String(deserializer);
    var var_review = sse_decode_opt_String(deserializer);
    var var_gtin = sse_decode_opt_String(deserializer);
    var var_coverPageIndex = sse_decode_i_32(deserializer);
    var var_pageCount = sse_decode_i_32(deserializer);
    return Metadata(
      title: var_title,
      series: var_series,
      issueNumber: var_issueNumber,
      seriesCount: var_seriesCount,
      volume: var_volume,
      alternateSeries: var_alternateSeries,
      alternateNumber: var_alternateNumber,
      alternateCount: var_alternateCount,
      summary: var_summary,
      notes: var_notes,
      year: var_year,
      month: var_month,
      day: var_day,
      writer: var_writer,
      penciller: var_penciller,
      inker: var_inker,
      colorist: var_colorist,
      letterer: var_letterer,
      coverArtist: var_coverArtist,
      editor: var_editor,
      translator: var_translator,
      publisher: var_publisher,
      imprint: var_imprint,
      genre: var_genre,
      tags: var_tags,
      web: var_web,
      languageIso: var_languageIso,
      format: var_format,
      blackAndWhite: var_blackAndWhite,
      manga: var_manga,
      characters: var_characters,
      teams: var_teams,
      locations: var_locations,
      mainCharacterOrTeam: var_mainCharacterOrTeam,
      scanInformation: var_scanInformation,
      storyArc: var_storyArc,
      storyArcNumber: var_storyArcNumber,
      seriesGroup: var_seriesGroup,
      ageRating: var_ageRating,
      communityRating: var_communityRating,
      review: var_review,
      gtin: var_gtin,
      coverPageIndex: var_coverPageIndex,
      pageCount: var_pageCount,
    );
  }

  @protected
  MetadataEditorSchemaFrb sse_decode_metadata_editor_schema_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_editorTitle = sse_decode_String(deserializer);
    var var_editable = sse_decode_bool(deserializer);
    var var_pdfMessage = sse_decode_opt_String(deserializer);
    var var_sections = sse_decode_list_metadata_section_spec_frb(deserializer);
    var var_ageRatingPresets = sse_decode_list_String(deserializer);
    return MetadataEditorSchemaFrb(
      editorTitle: var_editorTitle,
      editable: var_editable,
      pdfMessage: var_pdfMessage,
      sections: var_sections,
      ageRatingPresets: var_ageRatingPresets,
    );
  }

  @protected
  MetadataFieldKindFrb sse_decode_metadata_field_kind_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MetadataFieldKindFrb.values[inner];
  }

  @protected
  MetadataFieldSpecFrb sse_decode_metadata_field_spec_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_kind = sse_decode_metadata_field_kind_frb(deserializer);
    var var_required_ = sse_decode_bool(deserializer);
    var var_options = sse_decode_list_String(deserializer);
    var var_intMin = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_intMax = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_readOnlyValue = sse_decode_opt_String(deserializer);
    return MetadataFieldSpecFrb(
      id: var_id,
      label: var_label,
      kind: var_kind,
      required_: var_required_,
      options: var_options,
      intMin: var_intMin,
      intMax: var_intMax,
      readOnlyValue: var_readOnlyValue,
    );
  }

  @protected
  MetadataFieldValueFrb sse_decode_metadata_field_value_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fieldId = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return MetadataFieldValueFrb(fieldId: var_fieldId, value: var_value);
  }

  @protected
  MetadataSectionSpecFrb sse_decode_metadata_section_spec_frb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_fields = sse_decode_list_metadata_field_spec_frb(deserializer);
    return MetadataSectionSpecFrb(
      id: var_id,
      label: var_label,
      fields: var_fields,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageSummary sse_decode_page_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sortIndex = sse_decode_i_32(deserializer);
    var var_assetPath = sse_decode_String(deserializer);
    var var_absolutePath = sse_decode_String(deserializer);
    return PageSummary(
      id: var_id,
      sortIndex: var_sortIndex,
      assetPath: var_assetPath,
      absolutePath: var_absolutePath,
    );
  }

  @protected
  ProjectSettings sse_decode_project_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exportFormat = sse_decode_export_format_frb(deserializer);
    var var_inferredImportKind = sse_decode_inferred_import_kind_frb(
      deserializer,
    );
    var var_deleteProjectAfterExport = sse_decode_bool(deserializer);
    var var_useDefaultExportDirectory = sse_decode_bool(deserializer);
    var var_exportDirectory = sse_decode_opt_String(deserializer);
    var var_comicArchiveContainer = sse_decode_comic_archive_container_frb(
      deserializer,
    );
    var var_useComicArchiveExtension = sse_decode_bool(deserializer);
    return ProjectSettings(
      exportFormat: var_exportFormat,
      inferredImportKind: var_inferredImportKind,
      deleteProjectAfterExport: var_deleteProjectAfterExport,
      useDefaultExportDirectory: var_useDefaultExportDirectory,
      exportDirectory: var_exportDirectory,
      comicArchiveContainer: var_comicArchiveContainer,
      useComicArchiveExtension: var_useComicArchiveExtension,
    );
  }

  @protected
  ProjectSettingsUpdate sse_decode_project_settings_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exportFormat = sse_decode_export_format_frb(deserializer);
    var var_deleteProjectAfterExport = sse_decode_bool(deserializer);
    var var_useDefaultExportDirectory = sse_decode_bool(deserializer);
    var var_exportDirectory = sse_decode_opt_String(deserializer);
    var var_comicArchiveContainer = sse_decode_comic_archive_container_frb(
      deserializer,
    );
    var var_useComicArchiveExtension = sse_decode_bool(deserializer);
    return ProjectSettingsUpdate(
      exportFormat: var_exportFormat,
      deleteProjectAfterExport: var_deleteProjectAfterExport,
      useDefaultExportDirectory: var_useDefaultExportDirectory,
      exportDirectory: var_exportDirectory,
      comicArchiveContainer: var_comicArchiveContainer,
      useComicArchiveExtension: var_useComicArchiveExtension,
    );
  }

  @protected
  ProjectSummary sse_decode_project_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_updatedAtMs = sse_decode_i_64(deserializer);
    var var_coverThumbnailPath = sse_decode_opt_String(deserializer);
    return ProjectSummary(
      id: var_id,
      title: var_title,
      updatedAtMs: var_updatedAtMs,
      coverThumbnailPath: var_coverThumbnailPath,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_append_import_result(
    AppendImportResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.warnings, serializer);
    sse_encode_i_32(self.addedPageCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_metadata(
    Metadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_metadata(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_project_settings_update(
    ProjectSettingsUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project_settings_update(self, serializer);
  }

  @protected
  void sse_encode_comic_archive_container_frb(
    ComicArchiveContainerFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_export_format_frb(
    ExportFormatFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_import_cbz_result(
    ImportCbzResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project_summary(self.project, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_import_metadata_kind_frb(
    ImportMetadataKindFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_import_metadata_snapshot_frb(
    ImportMetadataSnapshotFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_import_metadata_kind_frb(self.kind, serializer);
    sse_encode_opt_String(self.xml, serializer);
  }

  @protected
  void sse_encode_inferred_import_kind_frb(
    InferredImportKindFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_metadata_field_spec_frb(
    List<MetadataFieldSpecFrb> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_metadata_field_spec_frb(item, serializer);
    }
  }

  @protected
  void sse_encode_list_metadata_field_value_frb(
    List<MetadataFieldValueFrb> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_metadata_field_value_frb(item, serializer);
    }
  }

  @protected
  void sse_encode_list_metadata_section_spec_frb(
    List<MetadataSectionSpecFrb> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_metadata_section_spec_frb(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_summary(
    List<PageSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project_summary(
    List<ProjectSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_metadata(Metadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.series, serializer);
    sse_encode_opt_String(self.issueNumber, serializer);
    sse_encode_opt_String(self.seriesCount, serializer);
    sse_encode_opt_String(self.volume, serializer);
    sse_encode_opt_String(self.alternateSeries, serializer);
    sse_encode_opt_String(self.alternateNumber, serializer);
    sse_encode_opt_String(self.alternateCount, serializer);
    sse_encode_opt_String(self.summary, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_opt_box_autoadd_i_32(self.year, serializer);
    sse_encode_opt_box_autoadd_i_32(self.month, serializer);
    sse_encode_opt_box_autoadd_i_32(self.day, serializer);
    sse_encode_opt_String(self.writer, serializer);
    sse_encode_opt_String(self.penciller, serializer);
    sse_encode_opt_String(self.inker, serializer);
    sse_encode_opt_String(self.colorist, serializer);
    sse_encode_opt_String(self.letterer, serializer);
    sse_encode_opt_String(self.coverArtist, serializer);
    sse_encode_opt_String(self.editor, serializer);
    sse_encode_opt_String(self.translator, serializer);
    sse_encode_opt_String(self.publisher, serializer);
    sse_encode_opt_String(self.imprint, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_opt_String(self.tags, serializer);
    sse_encode_opt_String(self.web, serializer);
    sse_encode_opt_String(self.languageIso, serializer);
    sse_encode_opt_String(self.format, serializer);
    sse_encode_opt_String(self.blackAndWhite, serializer);
    sse_encode_opt_String(self.manga, serializer);
    sse_encode_opt_String(self.characters, serializer);
    sse_encode_opt_String(self.teams, serializer);
    sse_encode_opt_String(self.locations, serializer);
    sse_encode_opt_String(self.mainCharacterOrTeam, serializer);
    sse_encode_opt_String(self.scanInformation, serializer);
    sse_encode_opt_String(self.storyArc, serializer);
    sse_encode_opt_String(self.storyArcNumber, serializer);
    sse_encode_opt_String(self.seriesGroup, serializer);
    sse_encode_opt_String(self.ageRating, serializer);
    sse_encode_opt_String(self.communityRating, serializer);
    sse_encode_opt_String(self.review, serializer);
    sse_encode_opt_String(self.gtin, serializer);
    sse_encode_i_32(self.coverPageIndex, serializer);
    sse_encode_i_32(self.pageCount, serializer);
  }

  @protected
  void sse_encode_metadata_editor_schema_frb(
    MetadataEditorSchemaFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.editorTitle, serializer);
    sse_encode_bool(self.editable, serializer);
    sse_encode_opt_String(self.pdfMessage, serializer);
    sse_encode_list_metadata_section_spec_frb(self.sections, serializer);
    sse_encode_list_String(self.ageRatingPresets, serializer);
  }

  @protected
  void sse_encode_metadata_field_kind_frb(
    MetadataFieldKindFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_metadata_field_spec_frb(
    MetadataFieldSpecFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_metadata_field_kind_frb(self.kind, serializer);
    sse_encode_bool(self.required_, serializer);
    sse_encode_list_String(self.options, serializer);
    sse_encode_opt_box_autoadd_i_32(self.intMin, serializer);
    sse_encode_opt_box_autoadd_i_32(self.intMax, serializer);
    sse_encode_opt_String(self.readOnlyValue, serializer);
  }

  @protected
  void sse_encode_metadata_field_value_frb(
    MetadataFieldValueFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fieldId, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_metadata_section_spec_frb(
    MetadataSectionSpecFrb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_list_metadata_field_spec_frb(self.fields, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_page_summary(PageSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.sortIndex, serializer);
    sse_encode_String(self.assetPath, serializer);
    sse_encode_String(self.absolutePath, serializer);
  }

  @protected
  void sse_encode_project_settings(
    ProjectSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_format_frb(self.exportFormat, serializer);
    sse_encode_inferred_import_kind_frb(self.inferredImportKind, serializer);
    sse_encode_bool(self.deleteProjectAfterExport, serializer);
    sse_encode_bool(self.useDefaultExportDirectory, serializer);
    sse_encode_opt_String(self.exportDirectory, serializer);
    sse_encode_comic_archive_container_frb(
      self.comicArchiveContainer,
      serializer,
    );
    sse_encode_bool(self.useComicArchiveExtension, serializer);
  }

  @protected
  void sse_encode_project_settings_update(
    ProjectSettingsUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_format_frb(self.exportFormat, serializer);
    sse_encode_bool(self.deleteProjectAfterExport, serializer);
    sse_encode_bool(self.useDefaultExportDirectory, serializer);
    sse_encode_opt_String(self.exportDirectory, serializer);
    sse_encode_comic_archive_container_frb(
      self.comicArchiveContainer,
      serializer,
    );
    sse_encode_bool(self.useComicArchiveExtension, serializer);
  }

  @protected
  void sse_encode_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.updatedAtMs, serializer);
    sse_encode_opt_String(self.coverThumbnailPath, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
