// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/metadata.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppendImportResult dco_decode_append_import_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  Metadata dco_decode_box_autoadd_metadata(dynamic raw);

  @protected
  ProjectSettingsUpdate dco_decode_box_autoadd_project_settings_update(
    dynamic raw,
  );

  @protected
  ComicArchiveContainerFrb dco_decode_comic_archive_container_frb(dynamic raw);

  @protected
  ExportFormatFrb dco_decode_export_format_frb(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportCbzResult dco_decode_import_cbz_result(dynamic raw);

  @protected
  ImportMetadataKindFrb dco_decode_import_metadata_kind_frb(dynamic raw);

  @protected
  ImportMetadataSnapshotFrb dco_decode_import_metadata_snapshot_frb(
    dynamic raw,
  );

  @protected
  InferredImportKindFrb dco_decode_inferred_import_kind_frb(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MetadataFieldSpecFrb> dco_decode_list_metadata_field_spec_frb(
    dynamic raw,
  );

  @protected
  List<MetadataFieldValueFrb> dco_decode_list_metadata_field_value_frb(
    dynamic raw,
  );

  @protected
  List<MetadataSectionSpecFrb> dco_decode_list_metadata_section_spec_frb(
    dynamic raw,
  );

  @protected
  List<PageSummary> dco_decode_list_page_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectSummary> dco_decode_list_project_summary(dynamic raw);

  @protected
  Metadata dco_decode_metadata(dynamic raw);

  @protected
  MetadataEditorSchemaFrb dco_decode_metadata_editor_schema_frb(dynamic raw);

  @protected
  MetadataFieldKindFrb dco_decode_metadata_field_kind_frb(dynamic raw);

  @protected
  MetadataFieldSpecFrb dco_decode_metadata_field_spec_frb(dynamic raw);

  @protected
  MetadataFieldValueFrb dco_decode_metadata_field_value_frb(dynamic raw);

  @protected
  MetadataSectionSpecFrb dco_decode_metadata_section_spec_frb(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PageSummary dco_decode_page_summary(dynamic raw);

  @protected
  ProjectSettings dco_decode_project_settings(dynamic raw);

  @protected
  ProjectSettingsUpdate dco_decode_project_settings_update(dynamic raw);

  @protected
  ProjectSummary dco_decode_project_summary(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppendImportResult sse_decode_append_import_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Metadata sse_decode_box_autoadd_metadata(SseDeserializer deserializer);

  @protected
  ProjectSettingsUpdate sse_decode_box_autoadd_project_settings_update(
    SseDeserializer deserializer,
  );

  @protected
  ComicArchiveContainerFrb sse_decode_comic_archive_container_frb(
    SseDeserializer deserializer,
  );

  @protected
  ExportFormatFrb sse_decode_export_format_frb(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportCbzResult sse_decode_import_cbz_result(SseDeserializer deserializer);

  @protected
  ImportMetadataKindFrb sse_decode_import_metadata_kind_frb(
    SseDeserializer deserializer,
  );

  @protected
  ImportMetadataSnapshotFrb sse_decode_import_metadata_snapshot_frb(
    SseDeserializer deserializer,
  );

  @protected
  InferredImportKindFrb sse_decode_inferred_import_kind_frb(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MetadataFieldSpecFrb> sse_decode_list_metadata_field_spec_frb(
    SseDeserializer deserializer,
  );

  @protected
  List<MetadataFieldValueFrb> sse_decode_list_metadata_field_value_frb(
    SseDeserializer deserializer,
  );

  @protected
  List<MetadataSectionSpecFrb> sse_decode_list_metadata_section_spec_frb(
    SseDeserializer deserializer,
  );

  @protected
  List<PageSummary> sse_decode_list_page_summary(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectSummary> sse_decode_list_project_summary(
    SseDeserializer deserializer,
  );

  @protected
  Metadata sse_decode_metadata(SseDeserializer deserializer);

  @protected
  MetadataEditorSchemaFrb sse_decode_metadata_editor_schema_frb(
    SseDeserializer deserializer,
  );

  @protected
  MetadataFieldKindFrb sse_decode_metadata_field_kind_frb(
    SseDeserializer deserializer,
  );

  @protected
  MetadataFieldSpecFrb sse_decode_metadata_field_spec_frb(
    SseDeserializer deserializer,
  );

  @protected
  MetadataFieldValueFrb sse_decode_metadata_field_value_frb(
    SseDeserializer deserializer,
  );

  @protected
  MetadataSectionSpecFrb sse_decode_metadata_section_spec_frb(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PageSummary sse_decode_page_summary(SseDeserializer deserializer);

  @protected
  ProjectSettings sse_decode_project_settings(SseDeserializer deserializer);

  @protected
  ProjectSettingsUpdate sse_decode_project_settings_update(
    SseDeserializer deserializer,
  );

  @protected
  ProjectSummary sse_decode_project_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_append_import_result(
    AppendImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_metadata(Metadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_project_settings_update(
    ProjectSettingsUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_archive_container_frb(
    ComicArchiveContainerFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_format_frb(
    ExportFormatFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_cbz_result(
    ImportCbzResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_metadata_kind_frb(
    ImportMetadataKindFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_metadata_snapshot_frb(
    ImportMetadataSnapshotFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_inferred_import_kind_frb(
    InferredImportKindFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_metadata_field_spec_frb(
    List<MetadataFieldSpecFrb> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_metadata_field_value_frb(
    List<MetadataFieldValueFrb> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_metadata_section_spec_frb(
    List<MetadataSectionSpecFrb> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_page_summary(
    List<PageSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_summary(
    List<ProjectSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata(Metadata self, SseSerializer serializer);

  @protected
  void sse_encode_metadata_editor_schema_frb(
    MetadataEditorSchemaFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_field_kind_frb(
    MetadataFieldKindFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_field_spec_frb(
    MetadataFieldSpecFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_field_value_frb(
    MetadataFieldValueFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_section_spec_frb(
    MetadataSectionSpecFrb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_page_summary(PageSummary self, SseSerializer serializer);

  @protected
  void sse_encode_project_settings(
    ProjectSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_settings_update(
    ProjectSettingsUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_summary(
    ProjectSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
