// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

Metadata getProjectMetadata({required String projectId}) => RustLib.instance.api
    .crateApiMetadataGetProjectMetadata(projectId: projectId);

Metadata updateProjectMetadata({
  required String projectId,
  required Metadata metadata,
}) => RustLib.instance.api.crateApiMetadataUpdateProjectMetadata(
  projectId: projectId,
  metadata: metadata,
);

Metadata metadataWithPageCount({
  required Metadata metadata,
  required int pageCount,
}) => RustLib.instance.api.crateApiMetadataMetadataWithPageCount(
  metadata: metadata,
  pageCount: pageCount,
);

Metadata metadataWithCoverPageIndex({
  required Metadata metadata,
  required int coverPageIndex,
}) => RustLib.instance.api.crateApiMetadataMetadataWithCoverPageIndex(
  metadata: metadata,
  coverPageIndex: coverPageIndex,
);

Metadata metadataWithDropdownField({
  required Metadata metadata,
  required String fieldId,
  String? value,
}) => RustLib.instance.api.crateApiMetadataMetadataWithDropdownField(
  metadata: metadata,
  fieldId: fieldId,
  value: value,
);

MetadataEditorSchemaFrb getMetadataEditorSchema({
  required ExportFormatFrb exportFormat,
}) => RustLib.instance.api.crateApiMetadataGetMetadataEditorSchema(
  exportFormat: exportFormat,
);

String metadataFieldDisplayValue({
  required Metadata metadata,
  required String fieldId,
}) => RustLib.instance.api.crateApiMetadataMetadataFieldDisplayValue(
  metadata: metadata,
  fieldId: fieldId,
);

Metadata mergeMetadataFromForm({
  required ExportFormatFrb exportFormat,
  required Metadata base,
  required List<MetadataFieldValueFrb> fieldValues,
  required int pageCount,
}) => RustLib.instance.api.crateApiMetadataMergeMetadataFromForm(
  exportFormat: exportFormat,
  base: base,
  fieldValues: fieldValues,
  pageCount: pageCount,
);

/// FRB Metadata DTO；字段与 [`MetadataRecord`] 对齐，经宏与 `MetadataRecord` 互转。
class Metadata {
  final String title;
  final String? series;
  final String? issueNumber;
  final String? seriesCount;
  final String? volume;
  final String? alternateSeries;
  final String? alternateNumber;
  final String? alternateCount;
  final String? summary;
  final String? notes;
  final int? year;
  final int? month;
  final int? day;
  final String? writer;
  final String? penciller;
  final String? inker;
  final String? colorist;
  final String? letterer;
  final String? coverArtist;
  final String? editor;
  final String? translator;
  final String? publisher;
  final String? imprint;
  final String? genre;
  final String? tags;
  final String? web;
  final String? languageIso;
  final String? format;
  final String? blackAndWhite;
  final String? manga;
  final String? characters;
  final String? teams;
  final String? locations;
  final String? mainCharacterOrTeam;
  final String? scanInformation;
  final String? storyArc;
  final String? storyArcNumber;
  final String? seriesGroup;
  final String? ageRating;
  final String? communityRating;
  final String? review;
  final String? gtin;
  final int coverPageIndex;
  final int pageCount;

  const Metadata({
    required this.title,
    this.series,
    this.issueNumber,
    this.seriesCount,
    this.volume,
    this.alternateSeries,
    this.alternateNumber,
    this.alternateCount,
    this.summary,
    this.notes,
    this.year,
    this.month,
    this.day,
    this.writer,
    this.penciller,
    this.inker,
    this.colorist,
    this.letterer,
    this.coverArtist,
    this.editor,
    this.translator,
    this.publisher,
    this.imprint,
    this.genre,
    this.tags,
    this.web,
    this.languageIso,
    this.format,
    this.blackAndWhite,
    this.manga,
    this.characters,
    this.teams,
    this.locations,
    this.mainCharacterOrTeam,
    this.scanInformation,
    this.storyArc,
    this.storyArcNumber,
    this.seriesGroup,
    this.ageRating,
    this.communityRating,
    this.review,
    this.gtin,
    required this.coverPageIndex,
    required this.pageCount,
  });

  static Future<Metadata> default_() =>
      RustLib.instance.api.crateApiMetadataMetadataDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      series.hashCode ^
      issueNumber.hashCode ^
      seriesCount.hashCode ^
      volume.hashCode ^
      alternateSeries.hashCode ^
      alternateNumber.hashCode ^
      alternateCount.hashCode ^
      summary.hashCode ^
      notes.hashCode ^
      year.hashCode ^
      month.hashCode ^
      day.hashCode ^
      writer.hashCode ^
      penciller.hashCode ^
      inker.hashCode ^
      colorist.hashCode ^
      letterer.hashCode ^
      coverArtist.hashCode ^
      editor.hashCode ^
      translator.hashCode ^
      publisher.hashCode ^
      imprint.hashCode ^
      genre.hashCode ^
      tags.hashCode ^
      web.hashCode ^
      languageIso.hashCode ^
      format.hashCode ^
      blackAndWhite.hashCode ^
      manga.hashCode ^
      characters.hashCode ^
      teams.hashCode ^
      locations.hashCode ^
      mainCharacterOrTeam.hashCode ^
      scanInformation.hashCode ^
      storyArc.hashCode ^
      storyArcNumber.hashCode ^
      seriesGroup.hashCode ^
      ageRating.hashCode ^
      communityRating.hashCode ^
      review.hashCode ^
      gtin.hashCode ^
      coverPageIndex.hashCode ^
      pageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Metadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          series == other.series &&
          issueNumber == other.issueNumber &&
          seriesCount == other.seriesCount &&
          volume == other.volume &&
          alternateSeries == other.alternateSeries &&
          alternateNumber == other.alternateNumber &&
          alternateCount == other.alternateCount &&
          summary == other.summary &&
          notes == other.notes &&
          year == other.year &&
          month == other.month &&
          day == other.day &&
          writer == other.writer &&
          penciller == other.penciller &&
          inker == other.inker &&
          colorist == other.colorist &&
          letterer == other.letterer &&
          coverArtist == other.coverArtist &&
          editor == other.editor &&
          translator == other.translator &&
          publisher == other.publisher &&
          imprint == other.imprint &&
          genre == other.genre &&
          tags == other.tags &&
          web == other.web &&
          languageIso == other.languageIso &&
          format == other.format &&
          blackAndWhite == other.blackAndWhite &&
          manga == other.manga &&
          characters == other.characters &&
          teams == other.teams &&
          locations == other.locations &&
          mainCharacterOrTeam == other.mainCharacterOrTeam &&
          scanInformation == other.scanInformation &&
          storyArc == other.storyArc &&
          storyArcNumber == other.storyArcNumber &&
          seriesGroup == other.seriesGroup &&
          ageRating == other.ageRating &&
          communityRating == other.communityRating &&
          review == other.review &&
          gtin == other.gtin &&
          coverPageIndex == other.coverPageIndex &&
          pageCount == other.pageCount;
}

class MetadataEditorSchemaFrb {
  final String editorTitle;
  final bool editable;
  final String? pdfMessage;
  final List<MetadataSectionSpecFrb> sections;
  final List<String> ageRatingPresets;

  const MetadataEditorSchemaFrb({
    required this.editorTitle,
    required this.editable,
    this.pdfMessage,
    required this.sections,
    required this.ageRatingPresets,
  });

  @override
  int get hashCode =>
      editorTitle.hashCode ^
      editable.hashCode ^
      pdfMessage.hashCode ^
      sections.hashCode ^
      ageRatingPresets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataEditorSchemaFrb &&
          runtimeType == other.runtimeType &&
          editorTitle == other.editorTitle &&
          editable == other.editable &&
          pdfMessage == other.pdfMessage &&
          sections == other.sections &&
          ageRatingPresets == other.ageRatingPresets;
}

enum MetadataFieldKindFrb {
  text,
  multilineText,
  integer,
  dropdown,
  readOnly,
  ageRating,
  coverPageIndex,
  pageCountInfo,
}

class MetadataFieldSpecFrb {
  final String id;
  final String label;
  final MetadataFieldKindFrb kind;
  final bool required_;
  final List<String> options;
  final int? intMin;
  final int? intMax;
  final String? readOnlyValue;

  const MetadataFieldSpecFrb({
    required this.id,
    required this.label,
    required this.kind,
    required this.required_,
    required this.options,
    this.intMin,
    this.intMax,
    this.readOnlyValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      kind.hashCode ^
      required_.hashCode ^
      options.hashCode ^
      intMin.hashCode ^
      intMax.hashCode ^
      readOnlyValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataFieldSpecFrb &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind &&
          required_ == other.required_ &&
          options == other.options &&
          intMin == other.intMin &&
          intMax == other.intMax &&
          readOnlyValue == other.readOnlyValue;
}

class MetadataFieldValueFrb {
  final String fieldId;
  final String value;

  const MetadataFieldValueFrb({required this.fieldId, required this.value});

  @override
  int get hashCode => fieldId.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataFieldValueFrb &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          value == other.value;
}

class MetadataSectionSpecFrb {
  final String id;
  final String label;
  final List<MetadataFieldSpecFrb> fields;

  const MetadataSectionSpecFrb({
    required this.id,
    required this.label,
    required this.fields,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataSectionSpecFrb &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          fields == other.fields;
}
