// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_import_outcome_to_result`, `import_metadata_snapshot_to_frb`, `import_outcome_to_result`, `project_settings_from_record`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String corePing() => RustLib.instance.api.crateApiSimpleCorePing();

void initLibrary({required String appDataDir}) =>
    RustLib.instance.api.crateApiSimpleInitLibrary(appDataDir: appDataDir);

ProjectSummary createProject({String? title}) =>
    RustLib.instance.api.crateApiSimpleCreateProject(title: title);

List<ProjectSummary> listProjects() =>
    RustLib.instance.api.crateApiSimpleListProjects();

ImportCbzResult importCbz({required String sourcePath}) =>
    RustLib.instance.api.crateApiSimpleImportCbz(sourcePath: sourcePath);

ImportCbzResult importCbr({required String sourcePath}) =>
    RustLib.instance.api.crateApiSimpleImportCbr(sourcePath: sourcePath);

ImportCbzResult importEpub({required String sourcePath}) =>
    RustLib.instance.api.crateApiSimpleImportEpub(sourcePath: sourcePath);

AppendImportResult appendCbz({
  required String projectId,
  required String sourcePath,
}) => RustLib.instance.api.crateApiSimpleAppendCbz(
  projectId: projectId,
  sourcePath: sourcePath,
);

AppendImportResult appendCbr({
  required String projectId,
  required String sourcePath,
}) => RustLib.instance.api.crateApiSimpleAppendCbr(
  projectId: projectId,
  sourcePath: sourcePath,
);

AppendImportResult appendEpub({
  required String projectId,
  required String sourcePath,
}) => RustLib.instance.api.crateApiSimpleAppendEpub(
  projectId: projectId,
  sourcePath: sourcePath,
);

Future<void> exportCbz({
  required String projectId,
  required String destinationPath,
  required bool deleteProjectAfterExport,
}) => RustLib.instance.api.crateApiSimpleExportCbz(
  projectId: projectId,
  destinationPath: destinationPath,
  deleteProjectAfterExport: deleteProjectAfterExport,
);

Future<void> exportEpub({
  required String projectId,
  required String destinationPath,
  required bool deleteProjectAfterExport,
}) => RustLib.instance.api.crateApiSimpleExportEpub(
  projectId: projectId,
  destinationPath: destinationPath,
  deleteProjectAfterExport: deleteProjectAfterExport,
);

void deleteProject({required String projectId}) =>
    RustLib.instance.api.crateApiSimpleDeleteProject(projectId: projectId);

void touchProject({required String projectId}) =>
    RustLib.instance.api.crateApiSimpleTouchProject(projectId: projectId);

ProjectSettings getProjectSettings({required String projectId}) =>
    RustLib.instance.api.crateApiSimpleGetProjectSettings(projectId: projectId);

ProjectSettings updateProjectSettings({
  required String projectId,
  required ProjectSettingsUpdate update,
}) => RustLib.instance.api.crateApiSimpleUpdateProjectSettings(
  projectId: projectId,
  update: update,
);

ProjectSettings updateProjectExportFormat({
  required String projectId,
  required ExportFormatFrb exportFormat,
}) => RustLib.instance.api.crateApiSimpleUpdateProjectExportFormat(
  projectId: projectId,
  exportFormat: exportFormat,
);

ProjectSettings changeProjectInferredImportKind({
  required String projectId,
  required InferredImportKindFrb inferredImportKind,
}) => RustLib.instance.api.crateApiSimpleChangeProjectInferredImportKind(
  projectId: projectId,
  inferredImportKind: inferredImportKind,
);

ImportMetadataSnapshotFrb getImportMetadataSnapshot({
  required String projectId,
}) => RustLib.instance.api.crateApiSimpleGetImportMetadataSnapshot(
  projectId: projectId,
);

List<PageSummary> addPageImages({
  required String projectId,
  required List<String> sourcePaths,
}) => RustLib.instance.api.crateApiSimpleAddPageImages(
  projectId: projectId,
  sourcePaths: sourcePaths,
);

List<PageSummary> listPages({required String projectId}) =>
    RustLib.instance.api.crateApiSimpleListPages(projectId: projectId);

void deletePage({required String projectId, required String pageId}) => RustLib
    .instance
    .api
    .crateApiSimpleDeletePage(projectId: projectId, pageId: pageId);

PageSummary replacePageImage({
  required String projectId,
  required String pageId,
  required String sourcePath,
}) => RustLib.instance.api.crateApiSimpleReplacePageImage(
  projectId: projectId,
  pageId: pageId,
  sourcePath: sourcePath,
);

List<PageSummary> reorderPages({
  required String projectId,
  required List<String> orderedPageIds,
}) => RustLib.instance.api.crateApiSimpleReorderPages(
  projectId: projectId,
  orderedPageIds: orderedPageIds,
);

class AppendImportResult {
  final List<String> warnings;
  final int addedPageCount;

  const AppendImportResult({
    required this.warnings,
    required this.addedPageCount,
  });

  @override
  int get hashCode => warnings.hashCode ^ addedPageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppendImportResult &&
          runtimeType == other.runtimeType &&
          warnings == other.warnings &&
          addedPageCount == other.addedPageCount;
}

enum ComicArchiveContainerFrb { zip, sevenZip, rar }

enum ExportFormatFrb { epub, comicArchive, pdf }

class ImportCbzResult {
  final ProjectSummary project;
  final List<String> warnings;

  const ImportCbzResult({required this.project, required this.warnings});

  @override
  int get hashCode => project.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportCbzResult &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          warnings == other.warnings;
}

enum ImportMetadataKindFrb { comicinfo, opf, none }

class ImportMetadataSnapshotFrb {
  final ImportMetadataKindFrb kind;
  final String? xml;

  const ImportMetadataSnapshotFrb({required this.kind, this.xml});

  @override
  int get hashCode => kind.hashCode ^ xml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportMetadataSnapshotFrb &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          xml == other.xml;
}

enum InferredImportKindFrb { images, comicArchive, epub, pdf }

class PageSummary {
  final String id;
  final int sortIndex;
  final String assetPath;
  final String absolutePath;

  const PageSummary({
    required this.id,
    required this.sortIndex,
    required this.assetPath,
    required this.absolutePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sortIndex.hashCode ^
      assetPath.hashCode ^
      absolutePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sortIndex == other.sortIndex &&
          assetPath == other.assetPath &&
          absolutePath == other.absolutePath;
}

class ProjectSettings {
  final ExportFormatFrb exportFormat;
  final InferredImportKindFrb inferredImportKind;
  final bool deleteProjectAfterExport;
  final bool useDefaultExportDirectory;
  final String? exportDirectory;
  final ComicArchiveContainerFrb comicArchiveContainer;
  final bool useComicArchiveExtension;

  const ProjectSettings({
    required this.exportFormat,
    required this.inferredImportKind,
    required this.deleteProjectAfterExport,
    required this.useDefaultExportDirectory,
    this.exportDirectory,
    required this.comicArchiveContainer,
    required this.useComicArchiveExtension,
  });

  @override
  int get hashCode =>
      exportFormat.hashCode ^
      inferredImportKind.hashCode ^
      deleteProjectAfterExport.hashCode ^
      useDefaultExportDirectory.hashCode ^
      exportDirectory.hashCode ^
      comicArchiveContainer.hashCode ^
      useComicArchiveExtension.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSettings &&
          runtimeType == other.runtimeType &&
          exportFormat == other.exportFormat &&
          inferredImportKind == other.inferredImportKind &&
          deleteProjectAfterExport == other.deleteProjectAfterExport &&
          useDefaultExportDirectory == other.useDefaultExportDirectory &&
          exportDirectory == other.exportDirectory &&
          comicArchiveContainer == other.comicArchiveContainer &&
          useComicArchiveExtension == other.useComicArchiveExtension;
}

/// Writable project workflow fields (`inferred_import_kind` is not changed here).
class ProjectSettingsUpdate {
  final ExportFormatFrb exportFormat;
  final bool deleteProjectAfterExport;
  final bool useDefaultExportDirectory;
  final String? exportDirectory;
  final ComicArchiveContainerFrb comicArchiveContainer;
  final bool useComicArchiveExtension;

  const ProjectSettingsUpdate({
    required this.exportFormat,
    required this.deleteProjectAfterExport,
    required this.useDefaultExportDirectory,
    this.exportDirectory,
    required this.comicArchiveContainer,
    required this.useComicArchiveExtension,
  });

  @override
  int get hashCode =>
      exportFormat.hashCode ^
      deleteProjectAfterExport.hashCode ^
      useDefaultExportDirectory.hashCode ^
      exportDirectory.hashCode ^
      comicArchiveContainer.hashCode ^
      useComicArchiveExtension.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSettingsUpdate &&
          runtimeType == other.runtimeType &&
          exportFormat == other.exportFormat &&
          deleteProjectAfterExport == other.deleteProjectAfterExport &&
          useDefaultExportDirectory == other.useDefaultExportDirectory &&
          exportDirectory == other.exportDirectory &&
          comicArchiveContainer == other.comicArchiveContainer &&
          useComicArchiveExtension == other.useComicArchiveExtension;
}

class ProjectSummary {
  final String id;
  final String title;
  final PlatformInt64 updatedAtMs;
  final String? coverThumbnailPath;

  const ProjectSummary({
    required this.id,
    required this.title,
    required this.updatedAtMs,
    this.coverThumbnailPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      updatedAtMs.hashCode ^
      coverThumbnailPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          updatedAtMs == other.updatedAtMs &&
          coverThumbnailPath == other.coverThumbnailPath;
}
